name: cern-ef-density
automanagednamespaces: 1
namespace:
  number: 1
  prefix: test-6ivjfj
  deletestalenamespaces: false
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
steps:
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: start
      labelSelector: group = throughput
    identifier: EfPodStartupLatency
    instances: []
  - method: WaitForControlledPodsRunning
    params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = throughput
    identifier: WaitForRunningEfDeployments
    instances: []
  - method: SchedulingThroughput
    params:
      action: start
      labelSelector: group = throughput
    identifier: SchedulingThroughput
    instances: []
  module:
    path: ""
    params: {}
  name: Starting Ef pod measurements
- phases:
  - namespacerange:
      min: 1
      max: 1
      basename: null
    replicaspernamespace: 1
    tuningset: UniformQPS
    objectbundle:
    - basename: ef-deployment
      objecttemplatepath: ef-density-deployment.yaml
      templatefillmap:
        CpuRequest: 1m
        Group: throughput
        Image: vmk-atds-registry-01.cern.ch/tbed/pause:3.4.1
        MemoryRequest: 10M
        Replicas: 100
        UseHostNetwork: false
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: Creating Ef pods
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: gather
    identifier: WaitForRunningEfDeployments
    instances: []
  module:
    path: ""
    params: {}
  name: Collecting Ef pod measurements
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: gather
    identifier: EfPodStartupLatency
    instances: []
  module:
    path: ""
    params: {}
  name: ""
- phases: []
  measurements:
  - method: SchedulingThroughput
    params:
      action: gather
    identifier: SchedulingThroughput
    instances: []
  module:
    path: ""
    params: {}
  name: ""
tuningsets:
- name: UniformQPS
  initialdelay: 0
  qpsload: null
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload:
    qps: 5e+08
    burst: 1000000000
chaosmonkey:
  nodefailure: null
